services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pgs3cr3t
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for the database

volumes:
  postgres-data:
    driver: local

